/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/_authenticated/admin/route'
import { Route as AdminLiveRouteImport } from './routes/_authenticated/admin/live'
import { Route as AdminRidesRouteImport } from './routes/_authenticated/admin/rides'
import { Route as AdminDriversRouteImport } from './routes/_authenticated/admin/drivers'
import { Route as AdminBroadcastRouteImport } from './routes/_authenticated/admin/broadcast'
import { Route as AdminPricingRouteImport } from './routes/_authenticated/admin/pricing'
import { Route as AdminRatingsRouteImport } from './routes/_authenticated/admin/ratings'
import { Route as AdminSuspiciousRouteImport } from './routes/_authenticated/admin/suspicious'
import { Route as AdminCitiesRouteImport } from './routes/_authenticated/admin/cities'
import { Route as AdminEmergenciesRouteImport } from './routes/_authenticated/admin/emergencies'
import { Route as AdminSupportRouteImport } from './routes/_authenticated/admin/support'
import { Route as AdminSettingsRouteImport } from './routes/_authenticated/admin/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AdminRoute,
} as any)

const AdminRidesRoute = AdminRidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => AdminRoute,
} as any)

const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)

const AdminBroadcastRoute = AdminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AdminRoute,
} as any)

const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)

const AdminRatingsRoute = AdminRatingsRouteImport.update({
  id: '/ratings',
  path: '/ratings',
  getParentRoute: () => AdminRoute,
} as any)

const AdminSuspiciousRoute = AdminSuspiciousRouteImport.update({
  id: '/suspicious',
  path: '/suspicious',
  getParentRoute: () => AdminRoute,
} as any)

const AdminCitiesRoute = AdminCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => AdminRoute,
} as any)

const AdminEmergenciesRoute = AdminEmergenciesRouteImport.update({
  id: '/emergencies',
  path: '/emergencies',
  getParentRoute: () => AdminRoute,
} as any)

const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)

const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AdminRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/rides': typeof AdminRidesRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/ratings': typeof AdminRatingsRoute
  '/admin/suspicious': typeof AdminSuspiciousRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/emergencies': typeof AdminEmergenciesRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/settings': typeof AdminSettingsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AdminRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/rides': typeof AdminRidesRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/ratings': typeof AdminRatingsRoute
  '/admin/suspicious': typeof AdminSuspiciousRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/emergencies': typeof AdminEmergenciesRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/settings': typeof AdminSettingsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/_authenticated': typeof AuthenticatedRoute
  '/_authenticated/admin': typeof AdminRoute
  '/_authenticated/admin/live': typeof AdminLiveRoute
  '/_authenticated/admin/rides': typeof AdminRidesRoute
  '/_authenticated/admin/drivers': typeof AdminDriversRoute
  '/_authenticated/admin/broadcast': typeof AdminBroadcastRoute
  '/_authenticated/admin/pricing': typeof AdminPricingRoute
  '/_authenticated/admin/ratings': typeof AdminRatingsRoute
  '/_authenticated/admin/suspicious': typeof AdminSuspiciousRoute
  '/_authenticated/admin/cities': typeof AdminCitiesRoute
  '/_authenticated/admin/emergencies': typeof AdminEmergenciesRoute
  '/_authenticated/admin/support': typeof AdminSupportRoute
  '/_authenticated/admin/settings': typeof AdminSettingsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin/live'
    | '/admin/rides'
    | '/admin/drivers'
    | '/admin/broadcast'
    | '/admin/pricing'
    | '/admin/ratings'
    | '/admin/suspicious'
    | '/admin/cities'
    | '/admin/emergencies'
    | '/admin/support'
    | '/admin/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin/live'
    | '/admin/rides'
    | '/admin/drivers'
    | '/admin/broadcast'
    | '/admin/pricing'
    | '/admin/ratings'
    | '/admin/suspicious'
    | '/admin/cities'
    | '/admin/emergencies'
    | '/admin/support'
    | '/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/_authenticated/admin/live'
    | '/_authenticated/admin/rides'
    | '/_authenticated/admin/drivers'
    | '/_authenticated/admin/broadcast'
    | '/_authenticated/admin/pricing'
    | '/_authenticated/admin/ratings'
    | '/_authenticated/admin/suspicious'
    | '/_authenticated/admin/cities'
    | '/_authenticated/admin/emergencies'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/settings'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AuthenticatedRoute: typeof AuthenticatedRoute
}

export interface AuthenticatedRouteChildren {
  AdminRoute: typeof AdminRoute
}

export interface AdminRouteChildren {
  AdminLiveRoute: typeof AdminLiveRoute
  AdminRidesRoute: typeof AdminRidesRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminBroadcastRoute: typeof AdminBroadcastRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminRatingsRoute: typeof AdminRatingsRoute
  AdminSuspiciousRoute: typeof AdminSuspiciousRoute
  AdminCitiesRoute: typeof AdminCitiesRoute
  AdminEmergenciesRoute: typeof AdminEmergenciesRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/auth': { id: '/auth'; path: '/auth'; fullPath: '/auth'; preLoaderRoute: typeof AuthRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated': { id: '/_authenticated'; path: ''; fullPath: ''; preLoaderRoute: typeof AuthenticatedRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated/admin': { id: '/_authenticated/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AdminRouteImport; parentRoute: typeof AuthenticatedRouteImport }
    '/_authenticated/admin/live': { id: '/_authenticated/admin/live'; path: '/live'; fullPath: '/admin/live'; preLoaderRoute: typeof AdminLiveRouteImport; parentRoute: typeof AdminRouteImport }
    '/_authenticated/admin/rides': { id: '/_authenticated/admin/rides'; path: '/rides'; fullPath: '/admin/rides'; preLoaderRoute: typeof AdminRidesRouteImport; parentRoute: typeof AdminRouteImport }
    '/_authenticated/admin/drivers': { id: '/_authenticated/admin/drivers'; path: '/drivers'; fullPath: '/admin/drivers'; preLoaderRoute: typeof AdminDriversRouteImport; parentRoute: typeof AdminRouteImport }
    '/_authenticated/admin/broadcast': { id: '/_authenticated/admin/broadcast'; path: '/broadcast'; fullPath: '/admin/broadcast'; preLoaderRoute: typeof AdminBroadcastRouteImport; parentRoute: typeof AdminRouteImport }
    '/_authenticated/admin/pricing': { id: '/_authenticated/admin/pricing'; path: '/pricing'; fullPath: '/admin/pricing'; preLoaderRoute: typeof AdminPricingRouteImport; parentRoute: typeof AdminRouteImport }
    '/_authenticated/admin/ratings': { id: '/_authenticated/admin/ratings'; path: '/ratings'; fullPath: '/admin/ratings'; preLoaderRoute: typeof AdminRatingsRouteImport; parentRoute: typeof AdminRouteImport }
    '/_authenticated/admin/suspicious': { id: '/_authenticated/admin/suspicious'; path: '/suspicious'; fullPath: '/admin/suspicious'; preLoaderRoute: typeof AdminSuspiciousRouteImport; parentRoute: typeof AdminRouteImport }
    '/_authenticated/admin/cities': { id: '/_authenticated/admin/cities'; path: '/cities'; fullPath: '/admin/cities'; preLoaderRoute: typeof AdminCitiesRouteImport; parentRoute: typeof AdminRouteImport }
    '/_authenticated/admin/emergencies': { id: '/_authenticated/admin/emergencies'; path: '/emergencies'; fullPath: '/admin/emergencies'; preLoaderRoute: typeof AdminEmergenciesRouteImport; parentRoute: typeof AdminRouteImport }
    '/_authenticated/admin/support': { id: '/_authenticated/admin/support'; path: '/support'; fullPath: '/admin/support'; preLoaderRoute: typeof AdminSupportRouteImport; parentRoute: typeof AdminRouteImport }
    '/_authenticated/admin/settings': { id: '/_authenticated/admin/settings'; path: '/settings'; fullPath: '/admin/settings'; preLoaderRoute: typeof AdminSettingsRouteImport; parentRoute: typeof AdminRouteImport }
  }
}

const adminRouteChildren: AdminRouteChildren = {
  AdminLiveRoute,
  AdminRidesRoute,
  AdminDriversRoute,
  AdminBroadcastRoute,
  AdminPricingRoute,
  AdminRatingsRoute,
  AdminSuspiciousRoute,
  AdminCitiesRoute,
  AdminEmergenciesRoute,
  AdminSupportRoute,
  AdminSettingsRoute,
}

const authenticatedRouteChildren: AuthenticatedRouteChildren = {
  AdminRoute: AdminRoute._addFileChildren(adminRouteChildren),
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AuthRoute,
  AuthenticatedRoute: AuthenticatedRoute._addFileChildren(authenticatedRouteChildren),
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
