/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminSuspiciousRouteImport } from './routes/_authenticated/admin/suspicious'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin/support'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminRidesRouteImport } from './routes/_authenticated/admin/rides'
import { Route as AuthenticatedAdminRatingsRouteImport } from './routes/_authenticated/admin/ratings'
import { Route as AuthenticatedAdminPricingRouteImport } from './routes/_authenticated/admin/pricing'
import { Route as AuthenticatedAdminLiveRouteImport } from './routes/_authenticated/admin/live'
import { Route as AuthenticatedAdminEmergenciesRouteImport } from './routes/_authenticated/admin/emergencies'
import { Route as AuthenticatedAdminDriversRouteImport } from './routes/_authenticated/admin/drivers'
import { Route as AuthenticatedAdminCitiesRouteImport } from './routes/_authenticated/admin/cities'
import { Route as AuthenticatedAdminBroadcastRouteImport } from './routes/_authenticated/admin/broadcast'
import { Route as ApiPublicTelegramRiderRouteImport } from './routes/api/public/telegram/rider'
import { Route as ApiPublicTelegramDriverRouteImport } from './routes/api/public/telegram/driver'
import { Route as ApiPublicCronPeakAlertsRouteImport } from './routes/api/public/cron/peak-alerts'
import { Route as ApiPublicCronAggregatePeaksRouteImport } from './routes/api/public/cron/aggregate-peaks'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSuspiciousRoute =
  AuthenticatedAdminSuspiciousRouteImport.update({
    id: '/suspicious',
    path: '/suspicious',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRidesRoute = AuthenticatedAdminRidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminRatingsRoute =
  AuthenticatedAdminRatingsRouteImport.update({
    id: '/ratings',
    path: '/ratings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPricingRoute =
  AuthenticatedAdminPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLiveRoute = AuthenticatedAdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminEmergenciesRoute =
  AuthenticatedAdminEmergenciesRouteImport.update({
    id: '/emergencies',
    path: '/emergencies',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDriversRoute =
  AuthenticatedAdminDriversRouteImport.update({
    id: '/drivers',
    path: '/drivers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCitiesRoute =
  AuthenticatedAdminCitiesRouteImport.update({
    id: '/cities',
    path: '/cities',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBroadcastRoute =
  AuthenticatedAdminBroadcastRouteImport.update({
    id: '/broadcast',
    path: '/broadcast',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicTelegramRiderRoute = ApiPublicTelegramRiderRouteImport.update({
  id: '/api/public/telegram/rider',
  path: '/api/public/telegram/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramDriverRoute = ApiPublicTelegramDriverRouteImport.update({
  id: '/api/public/telegram/driver',
  path: '/api/public/telegram/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronPeakAlertsRoute = ApiPublicCronPeakAlertsRouteImport.update({
  id: '/api/public/cron/peak-alerts',
  path: '/api/public/cron/peak-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronAggregatePeaksRoute =
  ApiPublicCronAggregatePeaksRouteImport.update({
    id: '/api/public/cron/aggregate-peaks',
    path: '/api/public/cron/aggregate-peaks',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/admin/cities': typeof AuthenticatedAdminCitiesRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/admin/emergencies': typeof AuthenticatedAdminEmergenciesRoute
  '/admin/live': typeof AuthenticatedAdminLiveRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/ratings': typeof AuthenticatedAdminRatingsRoute
  '/admin/rides': typeof AuthenticatedAdminRidesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/suspicious': typeof AuthenticatedAdminSuspiciousRoute
  '/api/public/cron/aggregate-peaks': typeof ApiPublicCronAggregatePeaksRoute
  '/api/public/cron/peak-alerts': typeof ApiPublicCronPeakAlertsRoute
  '/api/public/telegram/driver': typeof ApiPublicTelegramDriverRoute
  '/api/public/telegram/rider': typeof ApiPublicTelegramRiderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/admin/cities': typeof AuthenticatedAdminCitiesRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/admin/emergencies': typeof AuthenticatedAdminEmergenciesRoute
  '/admin/live': typeof AuthenticatedAdminLiveRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/ratings': typeof AuthenticatedAdminRatingsRoute
  '/admin/rides': typeof AuthenticatedAdminRidesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/suspicious': typeof AuthenticatedAdminSuspiciousRoute
  '/api/public/cron/aggregate-peaks': typeof ApiPublicCronAggregatePeaksRoute
  '/api/public/cron/peak-alerts': typeof ApiPublicCronPeakAlertsRoute
  '/api/public/telegram/driver': typeof ApiPublicTelegramDriverRoute
  '/api/public/telegram/rider': typeof ApiPublicTelegramRiderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/_authenticated/admin/cities': typeof AuthenticatedAdminCitiesRoute
  '/_authenticated/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/_authenticated/admin/emergencies': typeof AuthenticatedAdminEmergenciesRoute
  '/_authenticated/admin/live': typeof AuthenticatedAdminLiveRoute
  '/_authenticated/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/_authenticated/admin/ratings': typeof AuthenticatedAdminRatingsRoute
  '/_authenticated/admin/rides': typeof AuthenticatedAdminRidesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/suspicious': typeof AuthenticatedAdminSuspiciousRoute
  '/api/public/cron/aggregate-peaks': typeof ApiPublicCronAggregatePeaksRoute
  '/api/public/cron/peak-alerts': typeof ApiPublicCronPeakAlertsRoute
  '/api/public/telegram/driver': typeof ApiPublicTelegramDriverRoute
  '/api/public/telegram/rider': typeof ApiPublicTelegramRiderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin/broadcast'
    | '/admin/cities'
    | '/admin/drivers'
    | '/admin/emergencies'
    | '/admin/live'
    | '/admin/pricing'
    | '/admin/ratings'
    | '/admin/rides'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/suspicious'
    | '/api/public/cron/aggregate-peaks'
    | '/api/public/cron/peak-alerts'
    | '/api/public/telegram/driver'
    | '/api/public/telegram/rider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin/broadcast'
    | '/admin/cities'
    | '/admin/drivers'
    | '/admin/emergencies'
    | '/admin/live'
    | '/admin/pricing'
    | '/admin/ratings'
    | '/admin/rides'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/suspicious'
    | '/api/public/cron/aggregate-peaks'
    | '/api/public/cron/peak-alerts'
    | '/api/public/telegram/driver'
    | '/api/public/telegram/rider'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/admin/broadcast'
    | '/_authenticated/admin/cities'
    | '/_authenticated/admin/drivers'
    | '/_authenticated/admin/emergencies'
    | '/_authenticated/admin/live'
    | '/_authenticated/admin/pricing'
    | '/_authenticated/admin/ratings'
    | '/_authenticated/admin/rides'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/suspicious'
    | '/api/public/cron/aggregate-peaks'
    | '/api/public/cron/peak-alerts'
    | '/api/public/telegram/driver'
    | '/api/public/telegram/rider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronAggregatePeaksRoute: typeof ApiPublicCronAggregatePeaksRoute
  ApiPublicCronPeakAlertsRoute: typeof ApiPublicCronPeakAlertsRoute
  ApiPublicTelegramDriverRoute: typeof ApiPublicTelegramDriverRoute
  ApiPublicTelegramRiderRoute: typeof ApiPublicTelegramRiderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/suspicious': {
      id: '/_authenticated/admin/suspicious'
      path: '/suspicious'
      fullPath: '/admin/suspicious'
      preLoaderRoute: typeof AuthenticatedAdminSuspiciousRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/rides': {
      id: '/_authenticated/admin/rides'
      path: '/rides'
      fullPath: '/admin/rides'
      preLoaderRoute: typeof AuthenticatedAdminRidesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ratings': {
      id: '/_authenticated/admin/ratings'
      path: '/ratings'
      fullPath: '/admin/ratings'
      preLoaderRoute: typeof AuthenticatedAdminRatingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pricing': {
      id: '/_authenticated/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AuthenticatedAdminPricingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/live': {
      id: '/_authenticated/admin/live'
      path: '/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AuthenticatedAdminLiveRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/emergencies': {
      id: '/_authenticated/admin/emergencies'
      path: '/emergencies'
      fullPath: '/admin/emergencies'
      preLoaderRoute: typeof AuthenticatedAdminEmergenciesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/drivers': {
      id: '/_authenticated/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AuthenticatedAdminDriversRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cities': {
      id: '/_authenticated/admin/cities'
      path: '/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AuthenticatedAdminCitiesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/broadcast': {
      id: '/_authenticated/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AuthenticatedAdminBroadcastRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/telegram/rider': {
      id: '/api/public/telegram/rider'
      path: '/api/public/telegram/rider'
      fullPath: '/api/public/telegram/rider'
      preLoaderRoute: typeof ApiPublicTelegramRiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/driver': {
      id: '/api/public/telegram/driver'
      path: '/api/public/telegram/driver'
      fullPath: '/api/public/telegram/driver'
      preLoaderRoute: typeof ApiPublicTelegramDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/peak-alerts': {
      id: '/api/public/cron/peak-alerts'
      path: '/api/public/cron/peak-alerts'
      fullPath: '/api/public/cron/peak-alerts'
      preLoaderRoute: typeof ApiPublicCronPeakAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/aggregate-peaks': {
      id: '/api/public/cron/aggregate-peaks'
      path: '/api/public/cron/aggregate-peaks'
      fullPath: '/api/public/cron/aggregate-peaks'
      preLoaderRoute: typeof ApiPublicCronAggregatePeaksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminBroadcastRoute: typeof AuthenticatedAdminBroadcastRoute
  AuthenticatedAdminCitiesRoute: typeof AuthenticatedAdminCitiesRoute
  AuthenticatedAdminDriversRoute: typeof AuthenticatedAdminDriversRoute
  AuthenticatedAdminEmergenciesRoute: typeof AuthenticatedAdminEmergenciesRoute
  AuthenticatedAdminLiveRoute: typeof AuthenticatedAdminLiveRoute
  AuthenticatedAdminPricingRoute: typeof AuthenticatedAdminPricingRoute
  AuthenticatedAdminRatingsRoute: typeof AuthenticatedAdminRatingsRoute
  AuthenticatedAdminRidesRoute: typeof AuthenticatedAdminRidesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminSuspiciousRoute: typeof AuthenticatedAdminSuspiciousRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminBroadcastRoute: AuthenticatedAdminBroadcastRoute,
    AuthenticatedAdminCitiesRoute: AuthenticatedAdminCitiesRoute,
    AuthenticatedAdminDriversRoute: AuthenticatedAdminDriversRoute,
    AuthenticatedAdminEmergenciesRoute: AuthenticatedAdminEmergenciesRoute,
    AuthenticatedAdminLiveRoute: AuthenticatedAdminLiveRoute,
    AuthenticatedAdminPricingRoute: AuthenticatedAdminPricingRoute,
    AuthenticatedAdminRatingsRoute: AuthenticatedAdminRatingsRoute,
    AuthenticatedAdminRidesRoute: AuthenticatedAdminRidesRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
    AuthenticatedAdminSuspiciousRoute: AuthenticatedAdminSuspiciousRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronAggregatePeaksRoute: ApiPublicCronAggregatePeaksRoute,
  ApiPublicCronPeakAlertsRoute: ApiPublicCronPeakAlertsRoute,
  ApiPublicTelegramDriverRoute: ApiPublicTelegramDriverRoute,
  ApiPublicTelegramRiderRoute: ApiPublicTelegramRiderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
